from enum import StrEnum


class Systems(StrEnum):
    """
    Enum specifying the system (eg.

    Workday, ServiceNow, DnB, etc).
    """

    ARIBA = "ARIBA"
    BOX = "BOX"
    COUPA = "COUPA"
    DNB = "DNB"
    MICROSOFT = "MICROSOFT"
    ORACLE_HCM = "ORACLE_HCM"
    ORACLE_FUSION = "ORACLE_FUSION"
    SALESFORCE = "SALESFORCE"
    SAP_SUCCESSFACTORS = "SAP_SUCCESSFACTORS"
    SEISMIC = "SEISMIC"
    SERVICENOW = "SERVICENOW"
    WORKDAY = "WORKDAY"
    WATSON_COMMERCE = "WATSON_COMMERCE"
    STERLING_OMS = "STERLING_OMS"
    GOOGLE = "GOOGLE"
    JIRA = "JIRA"
    SLACK = "SLACK"
    SAP_S4_HANA = "SAP_S4_HANA"
    ARIBA_SOAP = "ARIBA_SOAP"
    ADOBEWORKFRONT = "ADOBEWORKFRONT"
    AMAZON_S3 = "AMAZON_S3"
    ZENDESK = "ZENDESK"
    GITHUB = "GITHUB"
    SALESLOFT = "SALESLOFT"
    ZOOMINFO = "ZOOMINFO"
    HUBSPOT = "HUBSPOT"
    IBM_PLANNING_ANALYTICS = "IBM_PLANNING_ANALYTICS"
    IBM_COS = "IBM_COS"
